{
 "title": "Bird Status 2",
 "description": "Metrics of BIRD routing daemon to use with Prometheus for use with https://github.com/czerwonk/bird_exporter",
 "tags": [ "AS202427" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(bird_protocol_prefix_import_count, instance)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 30, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "bird_protocol_up{proto=\"BGP\", instance=~\"$host\", ip_version=\"6\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "prefixes preferred",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "bird_protocol_prefix_preferred_count{proto=\"BGP\",instance=~\"$host\",ip_version=\"6\"}",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "{{name}}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 15, "w": 17, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "bird_protocol_uptime{proto=\"BGP\",instance=~\"$host\",ip_version=\"6\"}",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "{{name}}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  }
 ]
}